tlambert03/ome-types

pyproject.toml
setup.cfg

isort 5.0 both makes backwards-incompatible changes to the Python API and stops sorting and de-duplicating imports across blocks. I created an `isort-5` branch to just update to the new API, but then I realized the codegen output didn't look as nice. Maybe a minor issue, but you can decide which approach you prefer!

Pin isort version to 4.x due to big changes in 5.x

---

src/ome_autogen.py

This fixes the following runtime errors:
* Correctly set default to "None" for TiffData/UUID
and these typing errors:
* Cast default values for constrained integer attributes (both mypy and
pywright were complaining about this)
* Drop use of conlist in ROI/Union in favor of Field (only mypy noticed this)

Improve typing hints in generated code

---

testing/conftest.py
testing/test_autogen.py

This adds a `--nogen` option to the pytest command that lets you run tests on the pregenerated model code.  So you can:
1. run `python -m ome_autogen` to generate the model
2. muck about manually with the generated model at `src/ome_types/model`
3. run pytest with `pytest --nogen` to test against your manually edited code.
- ... use `pytest --nogen --runxfail` to see errors on skipped files
- ... use (e.g.)  `pytest --nogen --runxfail -k spim` to test a single xml

add --nogen option to run tests on pregenerated code

---

src/ome_autogen.py
src/ome_types/schema.py
testing/test_autogen.py

This gets seven more example files to pass. Annotations are next on my list. In the process of stretching the override system even further with a new slot I decided to refactor the entries into instances of a small new dataclass for better readability.

Make light sources and shapes work

---

mypy.ini
src/ome_autogen.py
src/ome_types/schema.py
testing/test_autogen.py

This was straightfoward except for the XMLAnnotation. I wanted to present the "any" XML sub-tree as something usable and not just a stringified serialization that would have to be re-parsed anyway. An xml.etree.ElementTree.Element object is perfect, however I had trouble getting the validation to work with that as the attribute type. I did have to tell Pydantic to allow arbitrary classes as types, but for some reason the isinstance check it does fails mysteriously. I typed it Any just to move on but it's something to revisit later.
I had to disable the mypy warn_unused_ignores setting because it's triggered by `value: Any = _no_default  # type: ignore`. With some work on the code generation that could be added back in later.

Make annotations work

---

src/ome_autogen.py
src/ome_types/dataclasses.py

This PR has us use our own `@ome_dataclass` decorator, which is a wrapper around `pydantic.dataclasses.dataclass`.  I've been working with custom dataclass decorators in napari recently and finding it useful/powerful.
This PR makes all of the "ID" fields optional, and if they are not provided, a valid ID will be autogenerated, incrementing from the previous IDs.  If one is provided, it is validated as usual.
```python
In [1]: from ome_types.model import Instrument   
In [2]: i = Instrument()  
In [3]: i.id                           
Out[3]: 'Instrument:1'
```
we could probably use this pattern to move other things from the `autogen.py`

make IDs optional, add ome_dataclass decorator

---

src/ome_autogen.py
src/ome_types/dataclasses.py
testing/test_autogen.py

This uses the new `@ome_dataclass` decorator to clean up all of the hacks for dataclass inheritance with non-default args.
Used to be:
```python
_no_default = object()
@ome_dataclass
class Point(Shape):
x: float = _no_default  # type: ignore
y: float = _no_default  # type: ignore
def __post_init__(self) -> None:
if self.y is _no_default:
raise TypeError("__init__ missing 1 required argument: 'y'")
if self.x is _no_default:
raise TypeError("__init__ missing 1 required argument: 'x'")
```
now is:
```python
from ome_types.dataclasses import EMPTY, ome_dataclass
@ome_dataclass
class Point(Shape):
x: float = EMPTY  # type: ignore
y: float = EMPTY  # type: ignore
```

better non-default in subclass solution

---

coverage.yml
src/ome_types/dataclasses.py

closes #4
This is a start on improved reprs, as per #4 (leave out properties that are set to the default, summarize containers rather than recursively include their contents) plenty to discuss here...
here's an `Image` repr as it stands:
```
Image:0
pixels=Pixels:0:0
dimension_order='XYCZT'
size_c=2
size_t=2
size_x=6
size_y=4
size_z=2
type='uint8'
bin_data=<8 Bin_Data>
channels=<2 Channels>
physical_size_x=10000.0
physical_size_y=10000.0
planes=<8 Planes>
acquisition_date=2010-11-10 14:42:38
annotation_ref=<4 Annotation_Ref>
instrument_ref=Instrument:SpimSampleMicroscope1
name=Spim Sample Tile 1 Angle 1
objective_settings=Objective:1
correction_collar=6.0
medium='Oil'
stage_label=StageLabel
name=(1,1) of 1x2
x=1.0
y=1.0
```
<details>
<summary>previously...</summary>
:joy:
``` …
```

improved repr

---

src/ome_autogen.py

This avoids an unnecessary network access and speeds up autogen a lot.

Use local copy of schema for autogen

---

src/ome_autogen.py

Switch from sets to lists in a few places to preserve insertion order.
Explicitly sort field_plurals.

Improve sorting of generated code for consistency

---

src/ome_autogen.py
src/ome_types/dataclasses.py

The id fields are no longer typed as Optional, but non-reference types can
still be constructed with the new auto-numbering and integer upgrade logic.
Reference types must always be constructed with a valid ID string.
Fixes #30

Make id fields non-optional but retain auto-numbering

---

src/ome_types/dataclasses.py

This makes interactive inspection a lot easier, compared to
`<object at 0x...>`.

Give sentinel objects a distinctive repr

---

src/ome_autogen.py
src/ome_types/dataclasses.py
src/ome_types/util.py

Adds a `.ref` to all `Reference` subclasses that returns the referenced model
object. There is an underlying `ref_` field to support this that is only filled 
in by the root `OME` object's constructor. A future API addition will be
created to support proper creation of References.
Closes #27

Update References with pointer to target object

---

setup.cfg
src/ome_types/dataclasses.py
testing/test_units.py

This still needs tests but I wanted to get your thoughts first. I didn't want to mess with the value fields and `..._unit` fields so I added a parallel property with the `_quantity` suffix for all fields with units.
Ultimately it would be cleaner to replace the value fields with a `pint.Quantity` and hide the `_unit` fields completely (that approach would work especially well for create/modify operations), but I'm not sure how we'd want to do the type annotations in that case. Pint doesn't play so well with typing as it loads unit definitions at runtime -- all you can do is type stuff as `Quantity`. We can definitely get Pydantic to parse quantities and reject incompatible units, but mypy probably won't be any help.
closes #3

Add _quantity property for values with units

---

pyproject.toml
setup.cfg
src/ome_autogen.py

this pulls annotations from the schema and renders them as numpy-style docstrings.  for instance:
```python
@ome_dataclass
class Objective(ManufacturerSpec):
"""A description of the microscope's objective lens.
Required elements include the lens numerical aperture, and the
magnification, both of which a floating point (real) numbers. The values
are those that are fixed for a particular objective: either because it
has been manufactured to this specification or the value has been
measured on this particular objective. Correction: This is the type of
correction coating applied to this lens. Immersion: This is the types of
immersion medium the lens is designed to work with. It is not the same as
'Medium' in ObjectiveRef (a single type) as here Immersion can have
compound values like 'Multi'. …
```

Add docstrings

---

docs/source/usage.rst
src/ome_autogen.py
src/ome_types/__init__.py
src/ome_types/schema.py
testing/test_model.py
testing/util.py

Now with backport of `ElementTree.canonicalize` from 3.8!

Add to_xml for serializing a model to XML

---

testing/data/tubhiswt.ome.xml
testing/test_model.py

see #45, this just adds the XML extracted from the first dataset [on this page](https://docs.openmicroscopy.org/ome-model/5.6.3/ome-tiff/data.html), and adds it to our `SHOULD_FAIL` tests.

add & skip failing test

---

src/ome_autogen.py
src/ome_types/schema.py
testing/data/tubhiswt.ome.xml
testing/test_model.py

fixes #35, fixes #49 
technically, if the list `item_type` isn't an `Enum`, this probably wouldn't work.  But that doesn't occur in the OME schema, so this solution will suffice for us.
Note: this creates a new problem for XML writing, I'll create a new issue for that.

fix xsd:list code gen

---

setup.cfg
src/ome_types/__init__.py

Also ignore Flake E203 since Black imposes some patterns that are incompatible
with it (and Black forces formatting for all cases that E203 covers, anyway).
Co-authored-by: Christoph Gohlke <cgohlke@uci.edu>

Switch from tifffile to inline TIFF-parsing code

---

setup.cfg
src/ome_types/__init__.py

adds a `from_tiff` convenience to generate an `OME` class from a tiff, using `tifffile`.  
Stopped short of adding `tifffile` to dependencies though (added an extra).  Ideas for extracting XML without `tifffile` welcome.

from_tiff convenience function

---

src/ome_types/schema.py
testing/util.py

This should fix the issue that @JacksonMaxfield had in https://github.com/tlambert03/ome-types/issues/50#issuecomment-728707062 ... wherein `ElementTree.parse()` is looking for a path name or file-like object, but receiving a literal xml string (when parsing structured_annotations).
cc @jmuhlich

fix etree parse on literal string

---

src/ome_types/schema.py

fixes #57  ... will open a new PR to add windows testing to CI

catch long string path exists fail

---

src/ome_autogen.py
src/ome_types/dataclasses.py
testing/test_model.py
testing/util.py

fixes #60 and pickling of OME objects with weakrefs by adding  `__getstate__` and `__setstate__` methods that de-reference re-reference the weakrefs.
I added tests, and most of them are passing, but a handful of them with xml annotations are still failing with a very weird message:
```
_pickle.PicklingError: Can't pickle <class 'xml.etree.ElementTree.Element'>: it's not the same object as xml.etree.ElementTree.Element
```
furthermore, I don't get that error when I do the test manually in ipython.  @jmuhlich,  would love to hear if you have any thoughts on what might be happening there.

Fix serialization/deserialization of weakrefs

---

pyproject.toml
setup.cfg
src/ome_autogen.py
src/ome_types/__init__.py
testing/test_model.py

closes #65 by remove pickle patches.  I also realized that xmlschema 1.4.2 has added a number of new issues by extending support for base64 types (and doing some other things with `python_type` that has broken our autogeneration.  so, until I have time to fix that, looks like we're pinned at 1.4.1.
I also tried to address #66 for a bit, but it wasn't as simple as just using `Element` as the type annotation.  will follow up

pin xmlschema to 1.4.1

---

src/ome_types/__init__.py

just want to be able to get the xml string from a tiff without immediately getting the OME object

Pull out `_tiff2xml` from `from_tiff`

---

.github/workflows/build.yml

This PR adds a github action that builds the source package and commits to the [`built` branch](https://github.com/tlambert03/ome-types/tree/built).  This makes it easier to link to the autogenerated code, and track how it changes over time.

Add a built branch

---

.github/scripts/download_aics_test_data.py
.github/workflows/test_aics.yml

since aicsimageio is probably one of the main users of this library, it'd be nice to know if I'm breaking anything as I iterate.  This adds a github action that runs some of the [aicsimageio/main](https://github.com/AllenCellModeling/aicsimageio/tree/main) branch tests whenever merging to master.
@JacksonMaxfield and @toloudis, would be good to get your input on this.  At the moment, I'm only running `pytest aicsimageio/tests/readers/test_ome_tiff_reader.py -v -k "not REMOTE"` ... but if you can point me to other tests that might directly or indirectly use `ome-types` functionality i can add them

Add aicsimageio test

---

src/ome_types/schema.py

partial fix for #88
This fixes the retrieval of a schema for a non 2016  OME schema (but doesn't yet extend support for the 2011 schema)

Fix retrieval of non 2016 OME schema

---

.pre-commit-config.yaml
setup.cfg
src/ome_types/_napari_plugin.py
testing/test_widget.py

This adds a napari plugin that will show the following XML tree viewer if you drop an `ome.xml` file onto napari

add xml viewer widget napari plugin

---

src/ome_autogen.py
src/ome_types/schema.py

This PR uses pydantic.color.Color for the internal representation of color.  this type is much nicer than the integer used by OME... and has a number of conveniences:
https://pydantic-docs.helpmanual.io/usage/types/#color-type

use pydantic Color type

---

setup.cfg
src/ome_autogen.py
src/ome_types/schema.py

this finally fixes the autogeneration for xmlschema versions > 1.5 (which changed some things about native python types)

Unpin xmlschema, fix for newer versions

---

src/ome_autogen.py
src/ome_types/_base_type.py
src/ome_types/schema.py
src/ome_types/util.py

This PR makes some changes to the way that Instrument/LightSourceGroup and ROI/Union are parsed.
most importantly, it removes the logic from `schema.element_decode` that prepares the dict "just right" so that it can be parsed by the pydantic model, and puts that logic in the validator on the respective models themselves...
This is working towards being able to support some additional "xml2dict" methods using things besides `xmlschema` (for instance, lxml, which is much faster).

Better abstract "group" types for Instrument and Union

---

setup.cfg
src/ome_types/_xmlschema.py

Hello everyone,
This PR removes the upper version bound of xmlschema and keeps compatibility with `1.x` versions.
Cheers,
Andreas 😃

build: Remove upper version bound of xmlschema dependency

---

pyproject.toml
src/ome_types/_convenience.py
src/ome_types/_lxml.py
src/ome_types/_xmlschema.py
tests/test_model.py
tests/test_serialization.py

This PR makes slight modifications to the `elem2dict` function that makes it compatible with both lxml as well as standard lib xml.etree elements.  I think the vast majority of the speedup of lxml compared to xmlschema parsing is the lack of schema validation.  (i saw ~25% speedup with lxml over xml.etree ... nice, but shouldn't be mandatory given that lxml can lag behind with updates)
My hope here, in the next couple PRs is to  disconnect the _validation_ of incoming xml from the _parsing_ of xml.  We could make both xmlschema and lxml optional (needed only for validation of an xml instance against the schema ... which we don't particularly need here, given that pydantic will do that on the dict object)

feat: make lxml optional (but don't yet remove from requirements)

---

tests/conftest.py
tests/test_omero_cli.py

fleshes out the fixture for testing omero-cli-transfer

test: more omero-cli tests

---

src/ome_types/_conversion.py
src/ome_types/_mixins/_base_type.py
src/ome_types/_mixins/_ome.py
tests/conftest.py
tests/test_model.py
tests/test_omero_cli.py

this solves the issue mentioned in https://forum.image.sc/t/ome-types-rewritten-requesting-alpha-testers/83174/28
where pydantic wasn't able to determine that a value had been "set" if it's a mutation of an existing sequence (e.g. `structured_annotations.append()`, leading to missing values in the xml output when `exclude_unset=True`

fix: fix missing set values in xml output

---

src/ome_types/_conversion.py
tests/test_from_xml.py
tests/test_ids.py
tests/test_model.py

aicsimageio has a few examples of xml with a lowercase "ome" in the schema name.  this fixes that

feat: catch and fix lowercase 'ome' in schemas

---

src/ome_types/_conversion.py
src/ome_types/etree_fixes.py
src/ome_types/fixes.py
tests/conftest.py
tests/data/MMStack.ome.xml
tests/test_model.py
tests/test_transforms.py

This PR addresses, and I'm going to say closes #129 
It adds a new `transformations` argument to `from_xml`
```py
AnyElementTree = xml.etree.ElementTree.ElementTree | lxml.etree._ElementTree
TransformationCallable = Callable[[AnyElementTree], AnyElementTree]
def from_xml(
...,
transformations: Iterable[TransformationCallable] = (),
):
```
which lets the user add any number of "fixers" before converting xml.  There is a new module `ome_types.etree_fixes` with some standard fixes, and PRs can be opened to add more.  So, to use them all:
```py
from ome_types import etree_fixes, from_xml
from_xml("some_bad.ome.xml", transformations=etree_fixes.ALL_FIXES)
```
**HOWEVER:**
With v0.4.0, many of the fixes that are included in the aicsimageio `clean_ome_xml_for_known_issues` function referenced in …

feat: add transformations to from_xml

---

src/xsdata_pydantic_basemodel/compat.py

remove the stray print warning about lxml attribute

fix: remove print

---

src/ome_types/_pydantic_compat.py
src/ome_types/_vendor/_pydantic_color_v2.py
src/xsdata_pydantic_basemodel/pydantic_compat.py
tests/test_autogen.py
tests/test_omero_cli.py

pydantic broke their own pydantic-extra-types library (and we had vendored it)

fix: fix import of removed private vendored attr in pydantic

---

src/ome_types/_pydantic_compat.py
src/xsdata_pydantic_basemodel/pydantic_compat.py

pydantic-compat v0.2 will move where the Field metadata key is:
https://github.com/pyapp-kit/pydantic-compat/pull/15
this prepares for that

feat: support pydantic-compat v0.2.

---

pyproject.toml
src/ome_autogen/generator.py
tests/conftest.py
tests/test_omero_cli.py

docs: fix plural names in docs

---

.github/workflows/test_dependents.yml
pyproject.toml
src/ome_autogen/main.py
src/ome_types/_pydantic_compat.py

fix: fix pydantic 2.10

---

src/ome_types/units.py

The OME schema defines "pt" as points but the pint default configuration makes it an alias for pints. This overrides the pt alias in our unit registry.
I added the option to ignore the override warning, also happy to discuss alternate approaches.

Fix pt unit being misinterpreted as pints

---

docs/usage.md

See https://github.com/ome/ome-model/issues/194
Initially illustrates the example of a single multi-Z, multi-T, multi-C image with one TIFF file per timepoint using the raw fluorescence images from idr0052 as the source (https://doi.org/10.17867/10000123a).
After downloading the raw TIFF files using the link provided, the `cell0005_R0001.companion.ome` should be readable by any software with OME-TIFF support e.g. ImageJ/Fiji via Bio-Formats, OMERO or others

docs: Add example of writing companion files using ome-types
